style: decrease "if" directory

diff --git a/sh/remove_submodule b/sh/remove_submodule
--- a/sh/remove_submodule
+++ b/sh/remove_submodule
@@ -30,35 +30,33 @@ source "$DOTFILES"/bash/functions
 if ! [[ -d .git ]]; then
   log_error "Not a Git repository"
   exit 1
+elif [[ $# -eq 0 ]]; then
+  log_error "No argument provided"
+  exit 1
 else
-  if [[ $# -eq 0 ]]; then
-      log_error "No argument provided"
-      exit 1
+  if [[ -d "$1" ]] && [[ -d .git/modules/"$1" ]]; then
+    log_manual_action "Do you wish to remove the submodule \"$1\"?"
+    select answer in "Yes" "No"; do
+      case $answer in
+        Yes) echo
+          git submodule deinit --force "$1"
+          git rm -rf "$1"
+          rm -rf .git/modules/"$1"
+          git commit -m "chore: remove submodule \"$1\""
+          git push
+          exit 0
+          ;;
+        No)
+          log_task "Abort"
+          exit 0
+          ;;
+        *)
+          log_error "Yes or No"
+          exit 1
+      esac
+    done
   else
-    if [[ -d "$1" ]] && [[ -d .git/modules/"$1" ]]; then
-      log_manual_action "Do you wish to remove the submodule \"$1\"?"
-      select answer in "Yes" "No"; do
-        case $answer in
-          Yes) echo
-            git submodule deinit --force "$1"
-            git rm -rf "$1"
-            rm -rf .git/modules/"$1"
-            git commit -m "chore: remove submodule \"$1\""
-            git push
-            exit 0
-            ;;
-          No)
-            log_task "Abort"
-            exit 0
-            ;;
-          *)
-            log_error "Yes or No"
-            exit 1
-        esac
-      done
-    else
-      log_error "No submodule found in the specified path \"$1\""
-      exit 1
-    fi
+    log_error "No submodule found in the specified path \"$1\""
+    exit 1
   fi
 fi
