fix: shellcheck suggestions

diff --git a/sh/remove_submodule b/sh/remove_submodule
--- a/sh/remove_submodule
+++ b/sh/remove_submodule
@@ -23,6 +23,7 @@
 
 set -eu
 
+# shellcheck disable=SC2154
 source "$DOTFILES"/bash/functions
 
 if ! [[ -d .git ]]; then
@@ -37,12 +38,15 @@ else
       log_task "Do you wish to remove the submodule \"$1\"?"
       select answer in "Yes" "No"; do
         case $answer in
-          Yes ) echo
+          Yes) echo
             git submodule deinit --force "$1"
             git rm -rf "$1"
             rm -rf .git/modules/"$1"
             exit 0 ;;
-          No ) exit 0;;
+          No) exit 0;;
+          *)
+            echo >&2 "Invalid choice: $answer"
+            exit 1
         esac
       done
     else
diff --git a/sh/serve_hugo_site b/sh/serve_hugo_site
--- a/sh/serve_hugo_site
+++ b/sh/serve_hugo_site
@@ -23,6 +23,7 @@
 
 set -eu
 
+# shellcheck disable=SC2154
 source "$DOTFILES"/bash/functions
 
 hugoserver () {
@@ -35,21 +36,24 @@ if ! [[ $# -eq 0 ]]; then
   log_manual_action "Not accept any argument."
   exit 1
 else
-  if [ -f ".hugo_build.lock" ]; then
+  if [[ -f ".hugo_build.lock" ]]; then
     if lsof -i:1313 ; then
       echo ---------------
       process_id="$(lsof -i:1313 | tail -1 | awk '{ print $2 }')"
       log_manual_action "ERROR: Port 1313 is in use by PID $process_id."
       log_task "Do you wish to kill that process?"
       select answer in "Yes" "No"; do
-      case $answer in
-        Yes ) echo
-          kill "$process_id"
-          echo Port 1313 is available now
-          hugoserver
-          exit 1;;
-        No ) exit 0;;
-      esac
+        case $answer in
+          Yes) echo
+            kill "$process_id"
+            echo Port 1313 is available now
+            hugoserver
+            exit 1;;
+          No) exit 0;;
+          *)
+            echo >&2 "Invalid choice: $answer"
+            exit 1
+        esac
       done
     else
       hugoserver
