style: put curly braces around variables

diff --git a/scripts/install_gnupg b/scripts/install_gnupg
--- a/scripts/install_gnupg
+++ b/scripts/install_gnupg
@@ -32,7 +32,7 @@ install_gnupg () {
   extracted_file="$(find /tmp/gnupg -type d -name "${1}-*")"
 
   # Run configure and makefile to install GnuPG
-  cd "$extracted_file" || return
+  cd "${extracted_file}" || return
   ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var
   make
   make check
@@ -90,7 +90,7 @@ nPth_tar="$( \
 # --------------------------------------------------------------------------------------
 # Install each package following the path/to/package_tar_file
 # --------------------------------------------------------------------------------------
-install_gnupg libgpg-error "$libgpg_error_tar"
+install_gnupg libgpg-error "${libgpg_error_tar}"
 
 # Since libgpg-error version 1.46, gpg-error-config is replaced by gpgrt-config.
 # For backward compatability, link these two files.
@@ -99,9 +99,9 @@ if [[ -f /usr/bin/gpgrt-config ]] && ! [[ -f /usr/bin/gpg-error-config ]]; then
   sudo ln -sf /usr/bin/gpgrt-config /usr/bin/gpg-error-config
 fi
 
-install_gnupg libgcrypt "$libgcrypt_tar"
-install_gnupg libksba "$libksba_tar"
-install_gnupg libassuan "$libassuan_tar"
-install_gnupg ntbtls "$ntbTLS_tar"
-install_gnupg npth "$nPth_tar"
-install_gnupg gnupg "$gnupg_tar"
+install_gnupg libgcrypt "${libgcrypt_tar}"
+install_gnupg libksba "${libksba_tar}"
+install_gnupg libassuan "${libassuan_tar}"
+install_gnupg ntbtls "${ntbTLS_tar}"
+install_gnupg npth "${nPth_tar}"
+install_gnupg gnupg "${gnupg_tar}"
