feat: colourise script output with log* functions

diff --git a/bash/functions b/bash/functions
--- a/bash/functions
+++ b/bash/functions
@@ -160,3 +160,63 @@ count_chars() {
   | sort --general-numeric-sort --reverse \
   | column
 }
+
+
+# ==== FUNCTION ========================================================================
+#         NAME: log*
+#  DESCRIPTION: Colourise terminal output
+#   PARAMETERS: Message
+#     EXAMPLES: log_task "Hello World"
+# ======================================================================================
+log_color() {
+  color_code="$1"
+  shift
+
+  printf "\033[${color_code}m%s\033[0m\n" "$*" >&2
+}
+
+log_red() {
+  log_color "0;31" "$@"
+}
+
+log_blue() {
+  log_color "0;34" "$@"
+}
+
+log_task() {
+  echo
+  log_blue "🔃" "$@"
+}
+
+log_manual_action() {
+  log_red "⚠️" "$@"
+}
+
+log_error() {
+  log_red "❌" "$@"
+}
+
+error() {
+  log_error "$@"
+  exit 1
+}
+
+
+# ==== FUNCTION ========================================================================
+#         NAME: sudo
+#  DESCRIPTION: Validate sudo
+#   PARAMETERS: ...
+#     EXAMPLES: sudo ...
+# ======================================================================================
+sudo() {
+  # shellcheck disable=SC2312
+  if [[ "$(id -u)" -eq 0 ]]; then
+    "$@"
+  else
+    if ! command sudo --non-interactive true 2>/dev/null; then
+      log_manual_action "Root privileges are required, please enter your password below"
+      command sudo --validate
+    fi
+    command sudo "$@"
+  fi
+}
diff --git a/sh/serve_hugo_site b/sh/serve_hugo_site
--- a/sh/serve_hugo_site
+++ b/sh/serve_hugo_site
@@ -20,6 +20,11 @@
 #
 # ======================================================================================
 
+
+set -eu
+
+source "$DOTFILES"/bash/functions
+
 hugoserver () {
   clear
   hugo server --disableFastRender --buildDrafts --buildExpired --buildFuture \
@@ -27,15 +32,15 @@ hugoserver () {
 }
 
 if ! [[ $# -eq 0 ]]; then
-  echo "Not accept any argument."
+  log_manual_action "Not accept any argument."
   exit 1
 else
   if [ -f ".hugo_build.lock" ]; then
     if lsof -i:1313 ; then
       echo ---------------
       process_id="$(lsof -i:1313 | tail -1 | awk '{ print $2 }')"
-      echo "ERROR: Port 1313 is in use by PID $process_id."
-      echo "Do you wish to kill that process?"
+      log_manual_action "ERROR: Port 1313 is in use by PID $process_id."
+      log_task "Do you wish to kill that process?"
       select answer in "Yes" "No"; do
       case $answer in
         Yes ) echo
@@ -50,7 +55,7 @@ else
       hugoserver
     fi
   else
-    echo "Not a Hugo project."
+    log_manual_action "Not a Hugo project."
     exit 1
   fi
 fi
